name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
      - main

jobs:
  turnstyle:
    name: Wait for previous deploys to finish
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: DFE-Digital/github-actions/turnstyle@master
        with:
          initial-wait-seconds: 12
          poll-interval-seconds: 20
          abort-after-seconds: 1800
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy to GOV.UK PaaS
    needs: turnstyle
    runs-on: ubuntu-latest
    env:
      APP_NAME: teaching-vacancies-prototype
    steps:
      - uses: actions/checkout@v2
      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: teaching-vacancies-prototype
      - name: Set GOV.UK Prototype Kit basic auth credentials
        env:
          PROTOTYPE_USERNAME: teaching
          PROTOTYPE_PASSWORD: vacancies
        run: |
          cf set-env ${{ env.APP_NAME }} USERNAME $PROTOTYPE_USERNAME
          cf set-env ${{ env.APP_NAME }} PASSWORD $PROTOTYPE_PASSWORD
      - name: Push application
        run: cf push
