name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  turnstyle:
    name: Wait for previous deploys to finish
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: DFE-Digital/github-actions/turnstyle@master
        with:
          initial-wait-seconds: 12
          poll-interval-seconds: 20
          abort-after-seconds: 1800
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy to GOV.UK PaaS
    needs: turnstyle
    runs-on: ubuntu-latest
    env:
      APP_NAME: teaching-vacancies-prototype
    steps:
      - uses: actions/checkout@v2
      - name: Set application environment (main branch)
        if: github.event_name == 'push'
        run: echo "CF_APP_NAME=teaching-vacancies-prototype" >> $GITHUB_ENV
      - name: Set application environment (Pull Request)
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: echo "CF_APP_NAME=teaching-vacancies-prototype-pr-$PR_NUMBER" >> $GITHUB_ENV
      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: teaching-vacancies-prototype
      - name: Push application
        run: cf push ${{ env.CF_APP_NAME }}
