name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
      - master

jobs:
  turnstyle:
    name: Wait for previous deploys to finish
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: softprops/turnstyle@v1
        name: Check workflow concurrency
        with:
          poll-interval-seconds: 20
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy to GOV.UK PaaS
    needs: turnstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: teaching-vacancies-prototype
      - name: Set GOV.UK Prototype Kit basic auth credentials
        env:
          PROTOTYPE_USERNAME: ${{ secrets.PROTOTYPE_USERNAME }}
          PROTOTYPE_PASSWORD: ${{ secrets.PROTOTYPE_PASSWORD }}
        run: |
          cf set-env teaching-vacancies-prototype USERNAME $PROTOTYPE_USERNAME
          cf set-env teaching-vacancies-prototype PASSWORD $PROTOTYPE_PASSWORD
      - name: Push application
        run: cf push
