name: Clean up GOV.UK PaaS review app

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  destroy_review:
    name: Destroy review app on merge
    runs-on: ubuntu-latest
    steps:
      - name: Set application environment
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: echo "CF_APP_NAME=teaching-vacancies-prototype-pr-$PR_NUMBER" >> $GITHUB_ENV
      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: teaching-vacancies-prototype
      - name: Delete application
        run: cf delete -r ${{ env.CF_APP_NAME }}
